volt.lo: /home/penlook/cmd/php/volt/ext/volt.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/penlook/cmd/php/volt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/penlook/cmd/php/volt/ext/volt.c -o volt.lo 
kernel/main.lo: /home/penlook/cmd/php/volt/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/penlook/cmd/php/volt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/penlook/cmd/php/volt/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /home/penlook/cmd/php/volt/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/penlook/cmd/php/volt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/penlook/cmd/php/volt/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /home/penlook/cmd/php/volt/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/penlook/cmd/php/volt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/penlook/cmd/php/volt/ext/kernel/exception.c -o kernel/exception.lo 
kernel/hash.lo: /home/penlook/cmd/php/volt/ext/kernel/hash.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/penlook/cmd/php/volt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/penlook/cmd/php/volt/ext/kernel/hash.c -o kernel/hash.lo 
kernel/debug.lo: /home/penlook/cmd/php/volt/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/penlook/cmd/php/volt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/penlook/cmd/php/volt/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /home/penlook/cmd/php/volt/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/penlook/cmd/php/volt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/penlook/cmd/php/volt/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /home/penlook/cmd/php/volt/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/penlook/cmd/php/volt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/penlook/cmd/php/volt/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /home/penlook/cmd/php/volt/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/penlook/cmd/php/volt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/penlook/cmd/php/volt/ext/kernel/array.c -o kernel/array.lo 
kernel/extended/array.lo: /home/penlook/cmd/php/volt/ext/kernel/extended/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/penlook/cmd/php/volt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/penlook/cmd/php/volt/ext/kernel/extended/array.c -o kernel/extended/array.lo 
kernel/string.lo: /home/penlook/cmd/php/volt/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/penlook/cmd/php/volt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/penlook/cmd/php/volt/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /home/penlook/cmd/php/volt/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/penlook/cmd/php/volt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/penlook/cmd/php/volt/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/extended/fcall.lo: /home/penlook/cmd/php/volt/ext/kernel/extended/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/penlook/cmd/php/volt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/penlook/cmd/php/volt/ext/kernel/extended/fcall.c -o kernel/extended/fcall.lo 
kernel/require.lo: /home/penlook/cmd/php/volt/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/penlook/cmd/php/volt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/penlook/cmd/php/volt/ext/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /home/penlook/cmd/php/volt/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/penlook/cmd/php/volt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/penlook/cmd/php/volt/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /home/penlook/cmd/php/volt/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/penlook/cmd/php/volt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/penlook/cmd/php/volt/ext/kernel/operators.c -o kernel/operators.lo 
kernel/math.lo: /home/penlook/cmd/php/volt/ext/kernel/math.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/penlook/cmd/php/volt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/penlook/cmd/php/volt/ext/kernel/math.c -o kernel/math.lo 
kernel/concat.lo: /home/penlook/cmd/php/volt/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/penlook/cmd/php/volt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/penlook/cmd/php/volt/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /home/penlook/cmd/php/volt/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/penlook/cmd/php/volt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/penlook/cmd/php/volt/ext/kernel/variables.c -o kernel/variables.lo 
kernel/filter.lo: /home/penlook/cmd/php/volt/ext/kernel/filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/penlook/cmd/php/volt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/penlook/cmd/php/volt/ext/kernel/filter.c -o kernel/filter.lo 
kernel/iterator.lo: /home/penlook/cmd/php/volt/ext/kernel/iterator.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/penlook/cmd/php/volt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/penlook/cmd/php/volt/ext/kernel/iterator.c -o kernel/iterator.lo 
kernel/time.lo: /home/penlook/cmd/php/volt/ext/kernel/time.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/penlook/cmd/php/volt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/penlook/cmd/php/volt/ext/kernel/time.c -o kernel/time.lo 
kernel/exit.lo: /home/penlook/cmd/php/volt/ext/kernel/exit.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/penlook/cmd/php/volt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/penlook/cmd/php/volt/ext/kernel/exit.c -o kernel/exit.lo 
volt/compiler.lo: /home/penlook/cmd/php/volt/ext/volt/compiler.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/penlook/cmd/php/volt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/penlook/cmd/php/volt/ext/volt/compiler.zep.c -o volt/compiler.lo 
phalcon/mvc/view/engine/volt/parser.lo: /home/penlook/cmd/php/volt/ext/phalcon/mvc/view/engine/volt/parser.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/penlook/cmd/php/volt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/penlook/cmd/php/volt/ext/phalcon/mvc/view/engine/volt/parser.c -o phalcon/mvc/view/engine/volt/parser.lo 
phalcon/mvc/view/engine/volt/scanner.lo: /home/penlook/cmd/php/volt/ext/phalcon/mvc/view/engine/volt/scanner.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/penlook/cmd/php/volt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/penlook/cmd/php/volt/ext/phalcon/mvc/view/engine/volt/scanner.c -o phalcon/mvc/view/engine/volt/scanner.lo 
$(phplibdir)/volt.la: ./volt.la
	$(LIBTOOL) --mode=install cp ./volt.la $(phplibdir)

./volt.la: $(shared_objects_volt) $(VOLT_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_volt) $(VOLT_SHARED_LIBADD)

